---
# tasks file for perfsonar-testpoint

#####
# Load OS dependant variables
#####
# This needs to be done for all tags
- name: Load variables based on OS type
  tags: [ 'ps::install', 'ps::running', 'ps::config' ]
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"

#####
# Configuration part: ps::config tag
#####
# Remove any conflictuous /etc/hosts configuration
- name: Make sure FQDN is not pointing to any localhost entry in /etc/hosts
  tags: [ 'ps::config' ]
  lineinfile:
    dest: /etc/hosts
    state: 'absent'
    regexp: '127\.0\..*[\s]+{{ ansible_fqdn }}[\s]+.*'

# NTP is essential for good measurements
- name: Configure additional NTP servers
  tags: [ 'ps::config' ]
  blockinfile:
    path: /etc/ntp.conf
    block: |
      server {{ item.hostname }} iburst
    marker: "# {mark} ansible-role-perfsonar {{ item.name }}"
  with_items: "{{ perfsonar_ntp_servers }}"
  notify:
    - restart ntp

- name: Disable ssh root access
  tags: [ 'ps::config' ]
  lineinfile:
    state: present
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin "
    line: "PermitRootLogin no"
  when: perfsonar_disable_root_ssh
  notify:
    - restart ssh

- name: Configure LS registration
  tags: [ 'ps::config' ]
  include: lsregistration.yml

- name: add/delete remote mesh configurations that have a valid URL and state
  tags: [ 'ps::config' ]
  include_tasks: psconfig_remotes.yml
  with_items: "{{ perfsonar_psconfig_remote_remotes | default([]) }}"
  when:
    - item.url | default('') != ''
    - item.state | default('present') in [ "absent", "present" ]

- name: auth interfaces with measurement archives
  tags: [ 'ps::config' ]
  include_tasks: auth_interface.yml
  with_items: "{{ ansible_all_ipv4_addresses | default([]) }}"
  loop_control:
    loop_var: auth_interface

#####
# Verifying part: ps::running tag
#####
# Make sure services are running, but first flush handlers to ensure services are restarted
- meta: flush_handlers

- pause:
    prompt: "Waiting 12 seconds for services to stabilise"
    seconds: 12
  tags: [ 'ps::running' ]

- name: Check that all perfSONAR services are running
  tags: [ 'ps::running' ]
  service:
    name: "{{ item }}"
    state: started
  with_flattened:
      - "{{ perfsonar_services }}"
      - "{{ perfsonar_os_specific_services }}"

# Run a few useful perfSONAR commands
# TODO: How to handle errors gracefully?
# i.e.: report the error, but do not stop playbook execution
- name: Collecting uptime information
  tags: [ 'ps::running', 'ps::monitor' ]
  shell: uptime
  register: uptime
  changed_when: False

- name: Get perfSONAR bundle type and version
  tags: [ 'ps::running', 'ps::monitor' ]
  shell: cat /var/lib/perfsonar/bundles/bundle_type /var/lib/perfsonar/bundles/bundle_version
  register: perfsonar_bundle_version
  changed_when: False

- name: Get pscheduler version
  tags: [ 'ps::running', 'ps::monitor' ]
  shell: pscheduler version | grep pscheduler-server
  register: pscheduler_version
  changed_when: False

- name: Report system information
  tags: [ 'ps::running', 'ps::monitor' ]
  vars:
    msg: |
      {{ansible_fqdn}} - {{uptime.stdout}}
      {{ansible_distribution}}-{{ansible_distribution_major_version}} - {{ansible_processor_cores}} cores - kernel {{ansible_kernel}}
      Memory (free/total in MB): {{ansible_memfree_mb}}/{{ansible_memtotal_mb}} (Swap: {{ansible_swapfree_mb}}/{{ansible_swaptotal_mb}})
      Running {{pscheduler_version.stdout}}
      From {{ perfsonar_bundle_version.stdout_lines | join (' bundle - version ') }}
  debug:
    msg:
      - "{{ msg[:-1].split('\n') }}"

- name: Run pscheduler troubleshoot locally
  tags: [ 'ps::running' ]
  command: pscheduler troubleshoot
  register: pscheduler_troubleshoot
  until: pscheduler_troubleshoot is succeeded
  retries: 3
  changed_when: False

- name: Report pscheduler troubleshoot output
  tags: [ 'ps::running', 'ps::monitor' ]
  debug:
    msg:
      - "{{ pscheduler_troubleshoot.stdout.replace('\n\n','\n').split('\n') }}"
  when: pscheduler_troubleshoot is defined

